# Context
app:
  name: "animal-service-api"
server:
  servlet:
    context-path: "/${app.name}"
  port: "8885"

# App version config use actuator lib
management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,info"

# Log pattern use lombok lib
logging:
  level:
    app: "DEBUG"
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SXXX}|%level|${app.name}|%X{X-Correlation-Id}|${PID}|%thread|%logger{40}|%message%n"